/**
 * Press kit / Studio assets — branded social-media images + AI captions
 * generated by the CMS Studio module from any platform content or About-page
 * source.
 *
 * One row per (content_type, content_id, template, size, slide_index)
 * combination. Captions are stored alongside the image so re-generation is
 * independent. The `caption_variants` JSONB holds 3 AI-generated variants per
 * platform; chosen_caption_* hold the user's picked/edited final text.
 */

import { pgTable, serial, text, integer, timestamp, uniqueIndex, jsonb, boolean } from "drizzle-orm/pg-core";

export interface CaptionVariants {
  /** Single platform-agnostic caption set (Studio 2026-05-31). Primary source. */
  neutral?: string[];
  // Legacy per-platform arrays — kept for back-compat; Studio mirrors `neutral`
  // into all three so older readers (ZIP, legacy press-kit) still work.
  x?: string[];
  ig?: string[];
  linkedin?: string[];
}

export const pressKitAssetsTable = pgTable(
  "press_kit_assets",
  {
    id: serial("id").primaryKey(),
    contentType: text("content_type").notNull(),
    contentId: integer("content_id").notNull(),
    template: text("template").notNull(),
    size: text("size").notNull(),
    r2Key: text("r2_key").notNull(),
    captionX: text("caption_x"),
    captionIg: text("caption_ig"),
    captionLi: text("caption_li"),
    generatedByUser: text("generated_by_user"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),

    // Studio v2 additions — additive, defaulted for backward compat
    templateFamily: text("template_family").notNull().default("item"),
    templateStyle: text("template_style").notNull().default("default"),
    slideIndex: integer("slide_index").notNull().default(0),
    slideCount: integer("slide_count").notNull().default(1),
    captionVariants: jsonb("caption_variants").$type<CaptionVariants>(),
    chosenCaptionX: text("chosen_caption_x"),
    chosenCaptionIg: text("chosen_caption_ig"),
    chosenCaptionLi: text("chosen_caption_li"),
    toneHint: text("tone_hint"),

    // Compose v2 — Layout × Slots model. `kitId` groups every (slide × size)
    // row produced by one Generate-kit click so a mixed carousel can be
    // reassembled. `layout` is the format the user picked; `useAiImage`
    // records whether slides were rendered as full-bleed AI backgrounds.
    layout: text("layout").notNull().default("single"),
    kitId: text("kit_id"),
    useAiImage: boolean("use_ai_image").notNull().default(false),
  },
  (t) => [
    uniqueIndex("press_kit_unique").on(t.contentType, t.contentId, t.template, t.size, t.slideIndex),
  ],
);

export type PressKitAsset = typeof pressKitAssetsTable.$inferSelect;
